from Charts import Chart
from PySide6.QtWidgets import *
from PySide6.QtGui import *
from PySide6.QtCore import *


class AlignDelegate(QStyledItemDelegate):     
    def initStyleOption(self, option, index):
        super(AlignDelegate, self).initStyleOption(option, index)
        option.displayAlignment = Qt.AlignCenter
        

class Widget1(QWidget):
    def __init__(self, parent=None):
        super(Widget1, self).__init__(parent)
        self.createTopWidget()
        self.createLeftWidget()
        self.createCenterWidget()
        self.createLeftBottomWidget()
        mainLayout = QGridLayout()
        mainLayout.addLayout(self.topLayout, 0, 0, 1, 10)
        mainLayout.addLayout(self.leftLayout, 1, 0, 2, 2)         #1, 0
        mainLayout.addLayout(self.centerLayout, 1, 2, 3, 10) #1, 1, 2, 7
        mainLayout.addLayout(self.leftBottomLayout, 2, 0, 3, 2)
        self.setLayout(mainLayout)
        self.setGeometry(100, 100, 1000, 900)     # 1920*1024
        self.setWindowTitle("Расчёт плана, продольного и поперечного профиля")
        mainLayout.setRowStretch(0, 0)                                
        mainLayout.setRowStretch(1, 1)   
        
    def createTopWidget(self) :
        label_1_1 = QLabel("Перегон")
        label_1_2 = QLabel("Путь")
        label_1_3 = QLabel("Машина")
        lineEdit_1_1 = QLineEdit()
        lineEdit_1_1.setFixedWidth(600)
        lineEdit_1_2 = QLineEdit()
        lineEdit_1_2.setFixedWidth(50)
        lineEdit_1_3 = QLineEdit()
        lineEdit_1_3.setFixedWidth(200)
        label_2_1 = QLabel("Начало")
        label_2_2 = QLabel("КМ+")
        label_2_3 = QLabel("М")
        label_2_4 = QLabel("Длина")
        label_2_5 = QLabel("М")
        label_2_6 = QLabel("Конец")
        label_2_7 = QLabel("КМ+")
        label_2_8 = QLabel("М")
        label_2_9 = QLabel("Дата")
        label_2_10 = QLabel("Прижим")
        lineEdit_2_1 = QLineEdit()
        lineEdit_2_1.setFixedWidth(30)
        lineEdit_2_2 = QLineEdit()
        lineEdit_2_2.setFixedWidth(30)
        lineEdit_2_3 = QLineEdit()
        lineEdit_2_3.setFixedWidth(60)
        lineEdit_2_4 = QLineEdit()
        lineEdit_2_4.setFixedWidth(30)
        lineEdit_2_5 = QLineEdit()
        lineEdit_2_5.setFixedWidth(60)
        lineEdit_2_6 = QLineEdit()
        lineEdit_2_6.setFixedWidth(100)
        lineEdit_2_7 = QLineEdit()
        lineEdit_2_7.setFixedWidth(60)          
        topHLayout_1 = QHBoxLayout()
        topHLayout_1.addWidget(label_1_1)
        topHLayout_1.addWidget(lineEdit_1_1)
        topHLayout_1.addWidget(label_1_2)
        topHLayout_1.addWidget(lineEdit_1_2)
        topHLayout_1.addWidget(label_1_3)
        topHLayout_1.addWidget(lineEdit_1_3)        
        topHLayout_2 = QHBoxLayout()
        topHLayout_2.addWidget(label_2_1)
        topHLayout_2.addWidget(lineEdit_2_1)
        topHLayout_2.addWidget(label_2_2)
        topHLayout_2.addWidget(lineEdit_2_2)
        topHLayout_2.addWidget(label_2_3)
        topHLayout_2.addStretch(1) 
        topHLayout_2.addWidget(label_2_4)
        topHLayout_2.addWidget(lineEdit_2_3)
        topHLayout_2.addWidget(label_2_5)
        topHLayout_2.addStretch(1) 
        topHLayout_2.addWidget(label_2_6)
        topHLayout_2.addWidget(lineEdit_2_4)
        topHLayout_2.addWidget(label_2_7)
        topHLayout_2.addWidget(lineEdit_2_5)
        topHLayout_2.addWidget(label_2_8)    
        topHLayout_2.addWidget(label_2_9)
        topHLayout_2.addWidget(lineEdit_2_6)
        topHLayout_2.addWidget(label_2_10)
        topHLayout_2.addWidget(lineEdit_2_7)        
        self.topLayout = QVBoxLayout()
        self.topLayout.addLayout(topHLayout_1)
        self.topLayout.addLayout(topHLayout_2)

    def createLeftWidget(self):
        self.leftLayout = QVBoxLayout()        
        button1 = QPushButton("План")
        button2 = QPushButton("Уровень")
        button3 = QPushButton("Профиль")
        groupbox = QGroupBox("Редактирование")
        vbox1 = QVBoxLayout()
        vbox1.addWidget(button1)
        vbox1.addWidget(button2)
        vbox1.addWidget(button3)
        groupbox.setLayout(vbox1)
        self.leftLayout.addWidget(groupbox)        
        button4 = QPushButton("Результаты")
        button5 = QPushButton("Установки")
        button6 = QPushButton("Печать")
        button7 = QPushButton("Выход (ESC)")
        self.leftLayout.addStretch(1)
        self.leftLayout.addWidget(button4)
        self.leftLayout.addStretch(1)
        self.leftLayout.addWidget(button5)
        self.leftLayout.addStretch(1)
        self.leftLayout.addWidget(button6)
        self.leftLayout.addStretch(3)
        self.leftLayout.addWidget(button7)
        self.leftLayout.addStretch(1)
        self.leftLayout.setContentsMargins(20, 10, 20, 10) #left, top, right, bottom

    def createCenterWidget(self):
        chart1 = Chart(1)
        chart2 = Chart(2)
        chart3 = Chart(3)
        chart4 = Chart(4)
        chart5 = Chart(5)
        self.centerLayout = QVBoxLayout()
        self.centerLayout.addWidget(chart1)
        self.centerLayout.addWidget(chart2)
        self.centerLayout.addWidget(chart3)
        self.centerLayout.addWidget(chart4)
        self.centerLayout.addWidget(chart5)

    def createLeftBottomWidget(self):
        textEdit = QTextEdit()
        label = QLabel("Масштаб")
        lineEdit = QLineEdit()
        lineEdit.setFixedWidth(50)
        self.leftBottomLayout = QVBoxLayout()
        HLayout = QHBoxLayout()
        HLayout.addWidget(label)
        HLayout.addWidget(lineEdit)
        HLayout.addStretch(1) 
        self.leftBottomLayout.addWidget(textEdit)
        self.leftBottomLayout.addLayout(HLayout)
        self.leftBottomLayout.setContentsMargins(20, 10, 20, 10)
        

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    gallery = Widget1()
    gallery.show()
    sys.exit(app.exec())
